version: '2.2'

services:
  grafana:
    image: grafana/grafana
    build:
      context: './grafana'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_TIME_FROM
      - GF_TIME_TO
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_AUTH_GOOGLE_CLIENT_ID
      - GF_AUTH_GOOGLE_CLIENT_SECRET
      - GF_AUTH_GOOGLE_ALLOWED_DOMAINS
      - GF_VARIABLES_JIRA_NAME=Jira
      - GF_VARIABLES_JIRA_VALUE=$JIRA_HOST
      - GF_VARIABLES_ORG_NAME=Org
      - GF_VARIABLES_ORG_VALUE=$GITHUB_ORG
      - GF_VARIABLES_BOARD_NAME=Board
      - GF_VARIABLES_BOARD_VALUE
      - GF_VARIABLES_BOARD_VALUES
      - GF_VARIABLES_TOPIC_NAME=Topic
      - GF_VARIABLES_TOPIC_VALUE
      - GF_VARIABLES_TOPIC_VALUES
    depends_on:
      - datasource
      - influxdb
    ports:
      - '3000:3000'

  influxdb:
    image: influxdb:1.5.4
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  chronograf:
    image: chronograf:latest
    ports:
      - 8888:8888
    command: '--influxdb-url=http://influxdb:8086'
    depends_on:
      - influxdb

  datasource:
    build:
      context: './datasource'
    ports:
      - '3002:3002'
    environment:
      - GITHUB_TOKEN
      - GITHUB_ORG
      - JIRA_HOST
      - JIRA_USER
      - JIRA_PASS
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DATABASE=datasource
    depends_on:
      - influxdb
volumes:
  grafana_data:
  influxdb_data: