version: '2.2'

services:
  grafana:
    image: grafana/grafana
    build:
      context: './grafana'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_AUTH_GOOGLE_CLIENT_ID
      - GF_AUTH_GOOGLE_CLIENT_SECRET
      - GF_AUTH_GOOGLE_ALLOWED_DOMAINS
      - GF_VARIABLES_JIRA_NAME=Jira
      - GF_VARIABLES_JIRA_VALUE=$JIRA_HOST
      - GF_VARIABLES_ORG_NAME=Org
      - GF_VARIABLES_ORG_VALUE=$GITHUB_ORG
      - GF_VARIABLES_BOARD_NAME=Board
      - GF_VARIABLES_BOARD_VALUE
      - GF_VARIABLES_BOARD_VALUES
      - GF_VARIABLES_TOPIC_NAME=Topic
      - GF_VARIABLES_TOPIC_VALUE
      - GF_VARIABLES_TOPIC_VALUES
    depends_on:
      - prometheus
      - datasource
    ports:
      - '3000:3000'

  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    #links:
    #  - github-exporter:metrics

  datasource:
    build:
      context: './datasource'
    ports:
      - '3002:3002'
    environment:
      - GITHUB_TOKEN
      - GITHUB_ORG
      - JIRA_HOST
      - JIRA_USER
      - JIRA_PASS

volumes:
  prometheus_data:
  grafana_data: