apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: foobar
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: false